"""
test_workflows.py
==================
Run a single- or multi-step VLM prompt workflow over a dataset.

This is a general-purpose workflow runner. A "workflow" is an ordered list of
prompt steps (configs/experiment.json → prompts.workflows); each step combines
inputs from the work item with content generated by earlier steps into a
prompt, runs inference, and parses the result for the next step. The
summarization workflows shipped below are just one example — the same
structure fits any task expressible as one or more prompt steps.

Overview
--------
For the configured dataset, this script:
  1. Builds a work queue — one item per unit of work (see build_work_queue).
  2. For each item, runs every workflow step in order (see process_item):
     build the prompt payload, run inference, parse the result.
  3. Feeds each step's parsed result forward as input to the next step.
  4. Prints the final parsed result, and — if the dataset configures an
     "output_dir" — saves every step's parsed tags (intermediate outputs
     plus the final "response_text") to <output_dir>/<workflow>/<item_id>.json.

Prompt tags
-----------
Each step's user prompt template can reference two kinds of tags, filled only when
the tag actually appears in that step's prompt template:

    item tag    e.g. {images} — filled from the work item itself (its inputs)
    parsed tag  e.g. {response_text} — filled from the previous step's parsed
                result. The default parser exposes its output as
                {response_text}; a step with a custom parser (see
                _STEP_PARSERS) can expose any other name. A parsed tag
                resolves only if that exact key comes back from the parser,
                so keep parser output keys and template tags in sync.

Example workflows (configs/experiment.json)
--------------------------------------------
    onestep_summary     1 step  — all images sent together, one summary back
    multisteps_summary  2 steps — step 1 describes the images (parsed as
                                  {image_summaries}); step 2 synthesises those
                                  into one summary

Configuration
-------------
  Top-level constants (edit directly in this file):
    WORKFLOW    — workflow key in configs/experiment.json (prompts.workflows)
    CLIENT_NAME — override the active client, e.g. "ollama/gemma3-4b", or "" for default
    DATASET     — dataset key in configs/experiment.json (datasets → <DATASET>.input_dir;
                  add "output_dir" there to save per-item results, else nothing is saved)
    DEBUG       — if True, write per-step payload snapshots to DEBUG_DIR

Usage
-----
    python src/test_workflows.py
    python src/test_workflows.py --workflow onestep_summary --client gemini/flash-2.5
    python src/test_workflows.py --dataset demo_images
"""

from __future__ import annotations

import re
import sys
import json
import time
import argparse
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from utils.config import Config
from backends import get_backend_from_config
from backends.request import ImageBlock, InferenceRequest, TextBlock


# ── Top-level constants — edit these to control which data is processed ─────
WORKFLOW    = "multisteps_summary"      # workflow key in configs/experiment.json → prompts.workflows
CLIENT_NAME = "gemini_vtx/flash-2.5"    # See example client names in test_backends.py; "" = use experiment.json's active client
CONFIG_PATH = "configs/experiment.json"

DATASET     = "demo_images"             # dataset key in configs/experiment.json → "datasets"
DEBUG       = True                      # True = dump each step's payload to DEBUG_DIR before inference
DEBUG_DIR   = "output/workflow_debug"

IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp"}


# ── Work queue ───────────────────────────────────────────────────────────────
def build_work_queue(dataset: dict, project_dir: Path) -> list[dict]:
    """Build the list of work items for one dataset.

    A work item is one unit the workflow runs over — here ``{"item_id",
    "images"}``. ``item_id`` must be unique per item: it names that item's
    saved output file (see run_pipeline). This demo dataset is a flat folder
    of images, so its whole input_dir becomes a single item named after the
    dataset. A real task swaps this function for a loader that reads the
    dataset's own metadata/manifest and yields many items (with a unique
    item_id each, in whatever shape that task's payload builder expects);
    the rest of the pipeline is unaffected.
    """
    input_dir = project_dir / dataset["input_dir"]
    images = sorted(p for p in input_dir.iterdir() if p.suffix.lower() in IMAGE_EXTENSIONS) if input_dir.is_dir() else []
    if not images:
        print(f"WARN: no images found in {input_dir.resolve()}")
        return []
    return [{"item_id": dataset["name"], "images": images}]


# ── Payload construction ──────────────────────────────────────────────────────
def build_step_payload(step: dict, images: list[Path], prev_result: dict | None) -> dict:
    """Build the prompt payload for one workflow step.

    Scans ``step["user"]`` for the tags it uses and fills only those. Two
    kinds of tags are supported:

        item tag    built explicitly from the work item. This template ships
                    a single item tag, {images} (inserted inline as
                    ImageBlocks); a new task adds its own item tags here.
        parsed tag  any other tag — resolved by looking up that exact name in
                    ``prev_result``, the previous step's parsed output.

    Raises KeyError if a template references a parsed tag the previous
    step's parser did not provide — a naming mismatch between a parser and
    a template should fail loudly rather than silently send an empty value.
    """
    template = step["user"]
    used = set(re.findall(r"\{(\w+)\}", template))

    # Item tags: built here from the work item (this template ships only {images}).
    item_tags = {"images"}
    placeholder_map: dict[str, str | list] = {}
    if "images" in used:
        placeholder_map["images"] = [ImageBlock(str(p)) for p in images]

    # Parsed tags: everything else must come from the previous step's parser.
    for tag in used - item_tags:
        if not prev_result or tag not in prev_result:
            raise KeyError(
                f"Step {step['id']!r} template uses {{{tag}}}, but the previous "
                f"step's parser did not return a '{tag}' key — check that the "
                f"parser registered for that step (see _STEP_PARSERS) produces it."
            )
        placeholder_map[tag] = prev_result[tag]

    # Inline-substitute string placeholders, then split on list placeholders
    # ({images}) so image blocks land exactly where the template puts them.
    str_map  = {ph: v for ph, v in placeholder_map.items() if isinstance(v, str)}
    list_map = {ph: v for ph, v in placeholder_map.items() if isinstance(v, list)}

    for ph, val in str_map.items():
        template = template.replace(f"{{{ph}}}", val)

    if list_map:
        ph_pattern = "|".join(rf"\{{{ph}\}}" for ph in list_map)
        tokens = re.split(rf"({ph_pattern})", template)
    else:
        tokens = [template]

    content: list[TextBlock | ImageBlock] = []
    for token in tokens:
        ph_name = token[1:-1] if token.startswith("{") and token.endswith("}") else None
        if ph_name in list_map:
            content.extend(list_map[ph_name])
        elif token.strip():
            content.append(TextBlock(token))

    return {"system_prompt": step["system"], "content": content}


def dump_payload_debug(payload: dict, step: dict, item_id: str, debug_dir: Path) -> None:
    """Write a human-readable .txt snapshot of a payload to debug_dir.

    Image blocks are rendered as ``[IMAGE: <filename>]`` to keep the file
    plain text. Output path: ``<debug_dir>/<item_id>_<step_id>.txt``
    """
    out_path = debug_dir / f"{item_id}_{step['id']}.txt"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        f"Step : {step['id']}",
        f"Item : {item_id}",
        "",
        "─" * 72,
        "SYSTEM PROMPT",
        "─" * 72,
        payload["system_prompt"].strip(),
        "",
        "─" * 72,
        "USER CONTENT",
        "─" * 72,
    ]
    for block in payload["content"]:
        lines.append(f"[IMAGE: {block.label}]" if isinstance(block, ImageBlock) else block.text)

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ── Inference ──────────────────────────────────────────────────────────────────
def run_step_payload(payload: dict, client: dict, backend) -> dict:
    """Submit one payload to the backend and return ``{"text": str, "logs": list[str]}``."""
    request = InferenceRequest(
        content=payload["content"],
        system_prompt=payload["system_prompt"],
        max_new_tokens=client["max_tokens"],
        temperature=client["temperature"],
        top_p=client["top_p"],
    )
    return backend.run(request)


# ── Response parsing ────────────────────────────────────────────────────────────
# A parser turns a step's raw model response into a dict of parsed tags. Every
# key it returns becomes a {tag} a later step's template can reference, and the
# final step's result is what run_pipeline prints (via "response_text").
def parse_response_text(response: str, step_id: str) -> dict:
    """Default parser: exposes the raw response, stripped, as {response_text}.

    A step that needs structured output or differently-named parsed tags
    (e.g. {image_summaries}, {scores}) registers its own parser in
    _STEP_PARSERS returning those keys instead.
    """
    return {"response_text": response.strip()}


def parse_image_summaries(response: str, step_id: str) -> dict:
    """Example custom parser (multisteps_summary step 1): exposes the response
    as {image_summaries}, matching the tag step 2's template references."""
    return {"image_summaries": response.strip()}


# Dispatch table — register a step-id here when its response needs a custom
# parser (structured parsing, or extra/differently-named parsed tags for a
# later step). Steps with no entry fall back to parse_response_text.
_STEP_PARSERS: dict[str, callable] = {
    "multisteps_summary_step1": parse_image_summaries,
}


def parse_step_response(response: str, step_id: str) -> dict:
    """Dispatch to the step's registered parser, else the default parser."""
    parser = _STEP_PARSERS.get(step_id, parse_response_text)
    return parser(response, step_id)


# ── Per-item pipeline ─────────────────────────────────────────────────────────
def process_item(
    step_prompts: list[dict],
    item: dict,
    client: dict,
    backend,
    debug_dir: Path | None = None,
) -> dict:
    """Run every workflow step for one item, feeding each step's output into the next.

    Every step runs once over the item. A step's parsed result becomes
    ``prev_result`` for the next step, so a later step's template can only
    reference tags the previous step's parser actually returns (see
    build_step_payload).

    Returns every step's parsed tags merged into one dict, so the result
    holds both intermediate outputs (e.g. {image_summaries}) and the final
    answer. The final step must produce "response_text" — the shared key
    run_pipeline prints and treats as each workflow's final answer.
    """
    images = item["images"]
    prev_result: dict | None = None
    outputs: dict = {}

    for step_idx, step in enumerate(step_prompts):
        print(f"    [step {step_idx + 1}/{len(step_prompts)}] running...")
        payload = build_step_payload(step, images, prev_result)
        if debug_dir is not None:
            dump_payload_debug(payload, step, item["item_id"], debug_dir)
        resp = run_step_payload(payload, client, backend)
        for line in resp.get("logs", []):
            print(f"      {line}")
        prev_result = parse_step_response(resp["text"], step["id"])
        outputs.update(prev_result)

    return outputs


# ── Main pipeline ────────────────────────────────────────────────────────────
def run_pipeline(
    workflow:     str = WORKFLOW,
    client_name:  str = CLIENT_NAME,
    dataset_name: str = DATASET,
    debug:        bool = DEBUG,
) -> None:
    cfg = Config(CONFIG_PATH)
    client  = cfg.get_client_by_name(client_name) if client_name else cfg.get_current_client()
    backend = get_backend_from_config(client)
    dataset = cfg.get_dataset_config(dataset_name)

    # Load all step prompts upfront — works for single-step and multi-step workflows.
    num_steps = len(cfg.get_workflow_steps(workflow))
    step_prompts = [
        {
            "id":     f"{workflow}_step{i + 1}",
            "system": cfg.get_step_text(workflow, i + 1, "system"),
            "user":   cfg.get_step_text(workflow, i + 1, "user"),
        }
        for i in range(num_steps)
    ]
    debug_dir = Path(DEBUG_DIR) / workflow if debug else None

    # Results are saved only when the dataset configures an "output_dir";
    # each item's merged outputs go to <output_dir>/<workflow>/<item_id>.json.
    out_dir = cfg.project_dir / dataset["output_dir"] / workflow if dataset.get("output_dir") else None
    if out_dir is not None:
        out_dir.mkdir(parents=True, exist_ok=True)

    work_items = build_work_queue(dataset, cfg.project_dir)

    print(f"Dataset  : {dataset_name}  ({dataset['input_dir']})")
    print(f"Workflow : {workflow}  ({num_steps} step{'s' if num_steps > 1 else ''})")
    print(f"Client   : {client['hosting']}/{client['name']}  ->  {client['model_id']}")
    print(f"Output   : {out_dir if out_dir is not None else '(not saving — no output_dir configured)'}")
    print(f"Queue    : {len(work_items)} item(s)\n")

    for item in work_items:
        print(f"[{item['item_id']}] {len(item['images'])} image(s)")
        t0 = time.monotonic()
        result = process_item(step_prompts, item, client, backend, debug_dir)
        elapsed = time.monotonic() - t0

        if out_dir is not None:
            (out_dir / f"{item['item_id']}.json").write_text(json.dumps(result, indent=2), encoding="utf-8")

        print(f"\n{'=' * 60}")
        print(f"RESULT — {item['item_id']}  ({elapsed:.1f}s)")
        print("=" * 60)
        print(result["response_text"])
        print()


# ── Entry point ──────────────────────────────────────────────────────────────
if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="Run a single- or multi-step VLM workflow over a configured dataset.")
    ap.add_argument("--workflow", default=WORKFLOW, help='Workflow key in experiment.json (default: "%(default)s").')
    ap.add_argument("--client", default=CLIENT_NAME, dest="client_name", metavar="HOSTING/MODEL",
                     help='Client override, e.g. "ollama/gemma3-4b". Empty = use config active client.')
    ap.add_argument("--dataset", default=DATASET, dest="dataset_name", metavar="NAME",
                     help='Dataset key in experiment.json → "datasets" (default: "%(default)s").')
    ap.add_argument("--debug", action="store_true", default=DEBUG, help="Dump per-step payload snapshots to DEBUG_DIR.")
    args = ap.parse_args()

    run_pipeline(workflow=args.workflow, client_name=args.client_name, dataset_name=args.dataset_name, debug=args.debug)
